#!/bin/bash
#<html><h1 style="text-align:center;"><font color="red">INSTALADOR AUTOMATICO V12 PREMIUM</font><br></h1><br> <h1 style="text-align:center;"><font color="red">CRIADOR CARLOS EDUARDOR @kadu183</font><br></h1><br> <h1 style="text-align:center;"><font color="red'>Fique Atento a instalação</font><br></h1><br>
echo "America/Sao_Paulo" > /etc/timezone
echo ln -fs /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime > /dev/null 2>&1
echo dpkg-reconfigure --frontend noninteractive tzdata > /dev/null 2>&1
apt-get update -y && apt-get install apache2 -y && apt-get install cron curl unzip -y && apt-get install php5 libapache2-mod-php5 php5-mcrypt -y > /dev/null 2>&1
apache2 restart 
apt-get install mysql-server -y 
mysql_install_db
mysql_secure_installation
echo '* * * * * root /usr/bin/php /var/www/html/pages/system/cron.php' >> /etc/crontab
echo '* * * * * root /usr/bin/php /var/www/html/pages/system/cron.ssh.php ' >> /etc/crontab
echo '* * * * * root /usr/bin/php /var/www/html/pages/system/cron.sms.php' >> /etc/crontab
echo '* * * * * root /usr/bin/php /var/www/html/pages/system/cron.online.ssh.php' >> /etc/crontab
echo '10 * * * * root /usr/bin/php /var/www/html/pages/system/cron.servidor.php' >> /etc/crontab
cd /var/www/html && wget http://zipshare.blob.core.windows.net/ae6ff9c7-ae59-4685-90e7-383c7748e426/Paine12.zip
cd /var/www/html && unzip Paine12.zip && rm Paine12.zip && rm index.html
chmod 777 /var/www/html/admin/pages/servidor
chmod 777 /var/www/html/admin/pages/bandeirar
chmod 777 /var/www/html/admin/pages/faturas
chmod 777 /var/www/html/admin/pages/system
chmod 777 /var/www/html/admin/pages/usuario
apt-get install phpmyadmin -y
php5enmod mcrypt
service apache2 restart
ln -s /usr/share/phpmyadmin /var/www/html/phpmyadmin
apt-get install libssh2-1-dev libssh2-php -y > /dev/null 2>&1
php -m |grep ssh2
apt-get install php5-curl > /dev/null 2>&1
service mysql restart && service apache2 restart
